foswiki_packages:
  - BlogPlugin
  - ClassificationPlugin
  - DateManipPlugin
  - DBCacheContrib
  - DBCachePlugin
  - DigestPlugin
  - DisqusPlugin
  - DocumentViewerPlugin
  - EditChapterPlugin
  - FarscrollContrib
  - FastCGIEngineContrib
  - FilesysVirtualPlugin
  - FilterPlugin
  - FlexFormPlugin
  - FlexWebListPlugin
  - GenPDFWeasyPlugin
  - GraphvizPlugin
  - GridLayoutPlugin
  - HyphenationPlugin
  - ImageGalleryPlugin
  - ImagePlugin
  - InfiniteScrollContrib
  - JQAjaxFormContrib
  - JQAutoColorContrib
  - JQAutoLogoutContrib
  - JQCodeInputContrib
  - JQDataTablesPlugin
  - JQMomentContrib
  - JQPackeryContrib
  - JQPhotoSwipeContrib
  - JQSelect2Contrib
  - JQSerialPagerContrib
  - JQTwistyContrib
  - JSTreeContrib
  - LikePlugin
  - ListyPlugin
  - LogDispatchContrib
  - MoreFormfieldsPlugin
  - MediaElementPlugin
  - MetaCommentPlugin
  - MetaDataPlugin
  - MimeIconPlugin
  - MultiLingualPlugin
  - NatSkin
  - NatSkinPlugin
  - NginxPageCachePlugin
  - NumberPlugin
  - PageOptimizerPlugin
  - QMPlugin
  - QRCodePlugin
  - RedDotPlugin
  - RenderPlugin
  - SectionListPlugin
  - SecurityHeadersPlugin
  - SendEmailPlugin
  - SetVariablePlugin
  - SocialSharePlugin
  - SolrPlugin
  - SpreadsheetReaderPlugin
  - StringifierContrib
  - TagCloudPlugin
  - TopicInteractionPlugin
  - TrashPlugin
  - TwoFactorAuthPlugin
  - WebCreatorPlugin
  - WebDAVContrib
  - WebFontsContrib
  - WebLinkPlugin
  - WikiWorkbenchContrib
  - XSendFileContrib

